-- CRYPTPACK 패키지 선언
CREATE OR REPLACE PACKAGE CRYPTPACK AS 
    -- 암호화 함수 패키지 구성
    FUNCTION ENCRYPT(STR VARCHAR2, HASH VARCHAR2) RETURN VARCHAR2;                                    
    -- 복호화 함수 패키지 구성
    FUNCTION DECRYPT(XCRYPT VARCHAR2, HASH VARCHAR2) RETURN VARCHAR2;    
END CRYPTPACK;
--==>> Package CRYPTPACK이(가) 컴파일되었습니다.

-- CRYPTPACK 패키지 몸체 구성
CREATE OR REPLACE PACKAGE BODY CRYPTPACK AS
    -- 전역 변수 구성
    CRYPTED_STRING VARCHAR2(2000);
    
    -- 암호화 함수 정의
    FUNCTION ENCRYPT(STR VARCHAR2, HASH VARCHAR2) RETURN VARCHAR2 IS
        PIECES_OF_EIGHT NUMBER := ((FLOOR(LENGTH(STR)/8 + .9)) * 8);    
    BEGIN
        DBMS_OBFUSCATION_TOOLKIT.DESENCRYPT
        ( 
            INPUT_STRING => RPAD(STR, PIECES_OF_EIGHT),     
            KEY_STRING => RPAD(HASH, 8, '#'),
            ENCRYPTED_STRING => CRYPTED_STRING
        );
        RETURN CRYPTED_STRING;     
    END ENCRYPT;
    
    -- 복호화 함수 정의
    FUNCTION DECRYPT(XCRYPT VARCHAR2, HASH VARCHAR2) RETURN VARCHAR2 IS
    BEGIN
        DBMS_OBFUSCATION_TOOLKIT.DESDECRYPT
        ( 
            INPUT_STRING => XCRYPT,
            KEY_STRING => RPAD(HASH, 8, '#'),
            DECRYPTED_STRING => CRYPTED_STRING
        );
        RETURN TRIM(CRYPTED_STRING);
    END DECRYPT;
END CRYPTPACK;



commit;
--==>> Package Body CRYPTPACK이(가) 컴파일되었습니다.
SELECT * FROM user_tab_privs WHERE table_name = 'DBMS_OBFUSCATION_TOOLKIT';
ALTER PACKAGE CRYPTPACK COMPILE;



ALTER PACKAGE CRYPTPACK COMPILE;
select *
from join_member;
SELECT object_name, status, object_type FROM user_objects WHERE object_name = 'CRYPTPACK';
ALTER PACKAGE CRYPTPACK COMPILE;

SHOW ERRORS PACKAGE BODY CRYPTPACK;
SELECT * FROM user_errors WHERE name = 'CRYPTPACK';

DESC JOIN_MEMBER;

ALTER TABLE JOIN_MEMBER MODIFY (JM_PW VARCHAR2(2000));


INSERT INTO JOIN_MEMBER(JM_SID, MEM_SID, JM_ID, JM_PW, JM_NAME, JM_SSN, JM_GENDER, JM_NICKNAME, JM_TEL, JM_ADDR1, JM_ADDR2, JM_ZIPCODE)
VALUES(SEQ_JM.NEXTVAL, '24', 'kimin', CRYPTPACK.ENCRYPT('java002', 'java002'), '김기민', '339339-1234567', 1, '깃달인', '010-5555-5467', '서울특별시 구구구구', '구구동', '33343');